# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readG <- function(file, n, cls) {
    .Call(`_qgg_readG`, file, n, cls)
}

readW <- function(file, n, cls, af) {
    .Call(`_qgg_readW`, file, n, cls, af)
}

getWlist <- function(file, n, cls, af) {
    .Call(`_qgg_getWlist`, file, n, cls, af)
}

freqbed <- function(file, n, mask, cls) {
    .Call(`_qgg_freqbed`, file, n, mask, cls)
}

summarybed <- function(file, n, cls, af, weights, y) {
    .Call(`_qgg_summarybed`, file, n, cls, af, weights, y)
}

bayes <- function(y, W, b, lambda, pi, gamma, vg, vb, ve, ssb_prior, sse_prior, nub, nue, updateB, updateE, updatePi, nit, method) {
    .Call(`_qgg_bayes`, y, W, b, lambda, pi, gamma, vg, vb, ve, ssb_prior, sse_prior, nub, nue, updateB, updateE, updatePi, nit, method)
}

sbayes <- function(wy, LD, b, lambda, yy, pi, vg, vb, ve, ssb_prior, sse_prior, nub, nue, updateB, updateE, updatePi, n, nit, method) {
    .Call(`_qgg_sbayes`, wy, LD, b, lambda, yy, pi, vg, vb, ve, ssb_prior, sse_prior, nub, nue, updateB, updateE, updatePi, n, nit, method)
}

sbayes_spa <- function(wy, ww, LDvalues, LDindices, b, lambda, mask, yy, pi, gamma, vg, vb, ve, ssb_prior, sse_prior, nub, nue, updateB, updateE, updatePi, updateG, adjustE, n, nit, nburn, method, algo, seed) {
    .Call(`_qgg_sbayes_spa`, wy, ww, LDvalues, LDindices, b, lambda, mask, yy, pi, gamma, vg, vb, ve, ssb_prior, sse_prior, nub, nue, updateB, updateE, updatePi, updateG, adjustE, n, nit, nburn, method, algo, seed)
}

sbayes_reg <- function(wy, ww, LDvalues, LDindices, b, lambda, mask, yy, pi, gamma, vg, vb, ve, ssb_prior, sse_prior, nub, nue, updateB, updateE, updatePi, updateG, adjustE, n, nit, nburn, method, algo) {
    .Call(`_qgg_sbayes_reg`, wy, ww, LDvalues, LDindices, b, lambda, mask, yy, pi, gamma, vg, vb, ve, ssb_prior, sse_prior, nub, nue, updateB, updateE, updatePi, updateG, adjustE, n, nit, nburn, method, algo)
}

grsbed <- function(file, n, cls, af, b) {
    .Call(`_qgg_grsbed`, file, n, cls, af, b)
}

mtgrsbed <- function(file, n, cls, af, scale, b) {
    .Call(`_qgg_mtgrsbed`, file, n, cls, af, scale, b)
}

mmult <- function(A, B) {
    .Call(`_qgg_mmult`, A, B)
}

mvrnorm <- function(sigma) {
    .Call(`_qgg_mvrnorm`, sigma)
}

rwishart <- function(df, S) {
    .Call(`_qgg_rwishart`, df, S)
}

riwishart <- function(df, S) {
    .Call(`_qgg_riwishart`, df, S)
}

mtbayes <- function(y, W, b, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, nit, method) {
    .Call(`_qgg_mtbayes`, y, W, b, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, nit, method)
}

mtsbayes <- function(wy, ww, yy, b, LDvalues, LDindices, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, method) {
    .Call(`_qgg_mtsbayes`, wy, ww, yy, b, LDvalues, LDindices, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, method)
}

mtblr <- function(wy, ww, yy, b, XXvalues, XXindices, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, method) {
    .Call(`_qgg_mtblr`, wy, ww, yy, b, XXvalues, XXindices, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, method)
}

solvebed <- function(file, n, cls, nit, af, b, lambda, y) {
    .Call(`_qgg_solvebed`, file, n, cls, nit, af, b, lambda, y)
}

mtsolvebed <- function(file, n, cls, nit, af, b, lambda, y) {
    .Call(`_qgg_mtsolvebed`, file, n, cls, nit, af, b, lambda, y)
}

pruneld <- function(file, ldsize, cls, p, threshold, r2) {
    .Call(`_qgg_pruneld`, file, ldsize, cls, p, threshold, r2)
}

pruneldmat <- function(file, ldsize, p, threshold, r2) {
    .Call(`_qgg_pruneldmat`, file, ldsize, p, threshold, r2)
}

cp <- function(W) {
    .Call(`_qgg_cp`, W)
}

psets <- function(msets, setstat, stat, np) {
    .Call(`_qgg_psets`, msets, setstat, stat, np)
}

